name: 3D Contribution Skyline
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: samihavahora05
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: output
          commit_message: "Update 3D contribution skyline"
          file_pattern: "profile-3d-contrib/*.svg"
